spring.application.name=sushi-shop-billing
server.port=8080

# Auto-created Local File Database (Tu dong luu du lieu vao thu muc ./data/horsebillingdb ma khong can cai SQL Server)
spring.datasource.url=jdbc:h2:file:./data/horsebillingdb;AUTO_SERVER=TRUE;MODE=MSSQLServer;CASE_INSENSITIVE_IDENTIFIERS=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# JPA / Hibernate Configuration for H2
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# H2 Console (Xem CSDL bang trinh duyet o che do App: http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Jackson Date Format Configuration
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=Asia/Ho_Chi_Minh
