# Default profile: 'app' (Embedded file database stored at ./data/horsebillingdb for standalone .exe app)
# Change active profile to 'web' for MS SQL Server database mode: spring.profiles.active=web
spring.profiles.active=app
